# Generated by Django 5.2.5 on 2025-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_new_arrivals_cta_label',
            field=models.CharField(default='Shop all', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_new_arrivals_cta_url',
            field=models.CharField(default='/products/', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_new_arrivals_limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_new_arrivals_title',
            field=models.CharField(default='New arrivals', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_top_categories_cta_label',
            field=models.CharField(default='View all', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_top_categories_cta_url',
            field=models.CharField(default='/products/', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_top_categories_limit',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_top_categories_title',
            field=models.CharField(default='Top categories', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_new_arrivals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_top_categories',
            field=models.BooleanField(default=True),
        ),
    ]
