# Generated by Django 5.2.5 on 2025-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_siteconfig_home_new_arrivals_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_1_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_1_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_2_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_2_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_3_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_cta_3_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
