# Generated by Django 5.2.5 on 2025-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_relatedproduct_product_related_products_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('from_product', models.F('to_product')), _negated=True), name='ck_no_self_related'),
        ),
    ]
