# Generated by Django 5.2.5 on 2025-09-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='site_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='products.siteconfig'),
        ),
    ]
