# Generated by Django 5.2.5 on 2026-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_heroslide_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Número en formato internacional, ej. 573192333702', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_prefill',
            field=models.CharField(blank=True, default='Quiero una asesoría en sus productos', max_length=200),
        ),
    ]
