# Generated by Django 5.2.5 on 2025-09-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_image_file_product_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_1', models.CharField(blank=True, max_length=160)),
                ('hero_subtitle_1', models.CharField(blank=True, max_length=240)),
                ('hero_image_1_url', models.URLField(blank=True, max_length=500)),
                ('hero_image_1_file', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_title_2', models.CharField(blank=True, max_length=160)),
                ('hero_subtitle_2', models.CharField(blank=True, max_length=240)),
                ('hero_image_2_url', models.URLField(blank=True, max_length=500)),
                ('hero_image_2_file', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_title_3', models.CharField(blank=True, max_length=160)),
                ('hero_subtitle_3', models.CharField(blank=True, max_length=240)),
                ('hero_image_3_url', models.URLField(blank=True, max_length=500)),
                ('hero_image_3_file', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.CheckConstraint(condition=models.Q(('image_url__isnull', False), ('image_file__isnull', False), _connector='OR'), name='ck_variantimage_has_url_or_file'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('variant',), name='uq_variantimage_main_per_variant'),
        ),
    ]
