# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_siteconfig_contact_phone_siteconfig_whatsapp_prefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(
                blank=True,
                help_text='Correo donde se reciben los mensajes del formulario de contacto',
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_smtp_user',
            field=models.EmailField(
                blank=True,
                help_text='Usuario SMTP (cuenta desde la que se envía). Si está vacío, se usa EMAIL_HOST_USER de settings.',
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_smtp_password',
            field=models.CharField(
                blank=True,
                help_text='Contraseña de aplicación SMTP (Outlook/Gmail). Si está vacío, se usa EMAIL_HOST_PASSWORD de settings.',
                max_length=120,
            ),
        ),
    ]
