# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_siteconfig_contact_email_smtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/variants/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_1_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='site/hero/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_2_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='site/hero/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_3_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='site/hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='site/hero/'),
        ),
    ]
